services:
  json-server:
    build:
      dockerfile: Dockerfile.json-server
    image: ghcr.io/hajba-balint/joke-jsonserver:0.2

    ports:
      - "3000:80"

  front-end: 
    build:
      dockerfile: Dockerfile.front-end
    image: ghcr.io/hajba-balint/joke-frontend:0.2

    ports:
      - "8001:80"